ASUS-AICS/LibMultiLabel

.gitignore, README.md, data_utils.py, evaluate.py, example_config/rcv1/cnn.yml, main.py, model.py, network/__init__.py, network/base.py, network/caml.py, network/cnn.py, network/inner.py, utils/__init__.py, utils/log.py, utils/utils.py
This is the first pull request.
=> Our first PR!

README.md, data_utils.py, evaluate.py, example_config/rcv1/cnn.yml, main.py, model.py
1. Change the data format
2. Remove code for handling MIMIC
3. Refactor data loading workflow to support single evaluation mode
=> Refactor data loading workflow and support single evaluation mode

data_utils.py, evaluate.py, main.py, metrics.py, model.py, network/caml.py, network/cnn.py, requirements.txt
1. Class `MultiLabelMetric` is removed as it has the same functionality as `FewShotMetrics`.
2. `FewShotMetrics`
- rename to `MultiLabelMetrics`
- remove all target groups (e.g., S, F, Z) : use `config.label_file` in the future (?)
3. Move all CAML-like metrics to `metrics.py`.
4. `requirements.txt`: Remove package `tabulate`.
=> Refactor evaluate.py.

evaluate.py, main.py, metrics.py, utils/utils.py
1. Remove unused function in `MultiLabelMetrics`.
2. `metric.py`: `len(tk)` to k
3. Output prediction (provide top1 ~top 100 with scores) in this format: 
`<label1>:<value1> <label2>:<value2> ...`
=> Update evaluate function & metrics.py

evaluate.py, metrics.py
Move all `P@k`, `R@k` into `precision_recall_at_ks`.
=> P@k ranking

README.md, example_config/MIMIC-50/caml_tune.yml, example_config/rcv1/cnn_tune.yml, search_params.py
1. Add monitor metric to tune reporter. Use `CLIReporter` to show all monitor metrics.
2. Issues on the result dir (e.g., `runs`)
- The result dir creates once in the script, this make conflict when running the program on multiple GPUs.
- Make the result dir always one level under the root directory.
3. Config
- Add missing arguments in `example_config/rcv1/cnn_tune.yml`. 
- Replace `random` with `basic_variant` to reduce the confusion between the search space and the search algorithm.
4. Add grid search example to README.
=> [Parameter search script] Fix issues in parallel and monitor metric.

README.md, search_params.py
1. Set the default value of `search_alg` to `None`. Otherwise, we cannot read `search_alg` from the config file.
2. README: update example for `search_params.py`: `random` -> `basic_variant`
=> search_alg

README.md, example_config/MIMIC-50/caml_tune.yml, example_config/rcv1/cnn_tune.yml, libmultilabel/data_utils.py, libmultilabel/evaluate.py, libmultilabel/model.py, main.py, search_params.py
1. LibMultiLabel
- `data_utils.load_or_build_text_dict`: set word embedding when building the `word_dict`.
-  Disable tqdm, log info, and print with `--silent`.
2.  Parameter selection script
- Load and download resources (e.g., vector_cache, dataset, word_dict, and label_dict) before running all trials.
- Add `embed_cache_dir` to set the default torchtext cache dir `LibMultiLabel/.vector_cache`.  
- Add test results to `CLIReporter`.
=> Load static resources before running all trials

example_config/MIMIC-50/caml_tune.yml, example_config/rcv1/cnn_tune.yml, search_params.py
1. Enable list of search spaces if the search algorithm is `grid_search`.
Example:
```
filter_sizes: ['grid_search', [[2], [4], [6], [8], [10]]]
```
2. Update `example_config/MIMIC-50/caml_tune.yml` like the one we have in the paper.
=> Enable list of search spaces for basic_variant.

example_config/MIMIC-50/caml_tune.yml, search_params.py
**Description**: If the search space is `grid_search`, the same grid will be repeated `num_samples` times.  Set the default `num_samples` to 1 in `caml_tune.yml`.
=> Set num_samples to 1 in caml_tune.yml

requirements_parameter_search.txt
**Description** Ray `1.4.0` 293G to save logs in `/tmp/ray` after running 480 experiments while `1.4.1` use only 11M + 40G in `Trainable_*`.
See here: https://discuss.ray.io/t/ray-tune-run-out-of-disk-tmp-ray/2678
=> Update ray version to 1.4.1.

libmultilabel/metrics.py, libmultilabel/model.py, main.py, search_params.py
- Fix `dump_log bug`:  dump test results in tag "val"
- Sort `precision_recall_monitored` such as P@1, P@3, P@5 in `metric.py`. 
- Change list of `metrics_thresholds` to one `metrics_threshold` (we use one threshold in production too)
=> [Hotfix] Fix dump_log bug

libmultilabel/metrics.py, main.py
1. Remove `metric_threshold` when calculating `top-k`.
2. Remove shuffle in the test loader. Please see this warning:
```
UserWarning: Your test_dataloader has `shuffle=True`, it is best practice to turn this off for val/test/predict dataloaders.
warnings.warn(*args, **kwargs)
```
3. Put one new line before the headers of the `tabulate_metrics`.
=> [Hotfix] metrics.py

example_config/MIMIC-50/caml.yml, example_config/MIMIC-50/caml_tune.yml, example_config/MIMIC-50/cnn.yml, libmultilabel/data_utils.py, main.py
**Description** 
(1) Normalize word embedding for both torchtext vectors and vectors from the `embed_file`.
(2) Rename `--normalize` to `--normalize_embed`.
=> [Hotfix] Normalize embedding

libmultilabel/data_utils.py
**Description** Use the original `embed_weights` to avoid floating point error while reading embedding from file.
1. `torch.Tensor(x).numpy()` is not x. Please find more info here:
https://github.com/pytorch/text/blob/a27bafe2bb0928dbcf66b2fb3a59d132960ca955/torchtext/vocab.py#L216
2. This issue affect the reproducibility of `VanillaCNN` in the `reproduce` branch.
=> Use embed_weights instead of vocab.vectors

torch_trainer.py
**Description** Use `config.shuffle` instead of shuffle in `train()`
=> [Hotfix] Use `config.shuffle` instead of shuffle

libmultilabel/nn/data_utils.py
**Description** Add `fillna('')` to deal with empty labels (L3368, 25712, 28087, and 29322).
=> [Hotfix] Empty labels in MIMIC-full data

libmultilabel/nn/nn_utils.py, libmultilabel/utils.py, main.py, torch_trainer.py
1. Fix bug in **main.py**: linear does not have `trainer.dataset`
2. Add `nn.nn_utils` for torch-related functions
- Add `init_trainer` and `init_model`
- Move `init_device` and `set_seed` here.
=> Move torch-related functions to `nn.nn_utils.py`

docs/api/api.rst, docs/api/linear.rst, docs/api/nn.rst, docs/api/nn_networks.rst
1. `docs/api/nn_networks.rst`: Add document for `BiGRU`, `CAML`, `KimCNN`, and `XMLCNN`.
2. Replace `Methods` to `Module` which aligns to names we used at the beginning of `Using APIs`.
=> Add document for networks

example_config/MIMIC-50/caml_tune.yml, example_config/rcv1/cnn_tune.yml, search_params.py
1. Load config from file and overwrite values specified in CLI.
2. Remove `config: ` from the config file.
3. Naming: args from argparse, config from file
=> Clean config for search_params

libmultilabel/nn/data_utils.py, main.py
To have consistent behaviour across linear and nn.
`nn.data_utils.load_datasets` might need to be updated, in particular, the default argument being `None`.
=> Moved path logic to main

example_config/MIMIC-50/caml_tune.yml, example_config/rcv1/cnn_tune.yml, libmultilabel/nn/nn_utils.py, search_params.py, torch_trainer.py
1.  Remove hardcoded calls with Pytorch lightning callback.
- Instead of reporting the val score in the Trainable class, report on `validation_end`.
2. Enable `ASHAScheduler` in `search_params.py`.  
3. Merge tune's log dir with LibMultiLabel's.
=> Tune lightning & add ASHAScheduler

search_params.py
**Description**: Values in the nested config (i.e., `config["network_config"]["dropout"]`) is `None` when printing the current best trail in ray.  
The reason is that there isn't a recursive lookup here:
https://github.com/ray-project/ray/blob/4ef0d4a37a42c529af98b0cfb31e505b51088395/python/ray/tune/progress_reporter.py#L790
This can be resolved by copying these values to the first level of the config:
```yaml
network_config:
dropout: 0.2 # for libmultilabel
network_config/dropout: 0.2 # for ray
```
=> Fix issue on printing the current best trail

README.md, docs/cli/ov_data_format.rst, libmultilabel/linear/__init__.py, libmultilabel/linear/metrics.py, libmultilabel/utils.py, linear_trainer.py, main.py, search_params.py
Based on #131.
Refactored linear code from `main.py` to `linear_trainer.py`.
Rewrote `AttributeDict` from `pytorch_lightning.utilities.parsing.AttributeDict` in `main.py`.
Linear is now runnable with
```bash
pip install scikit-learn liblinear-multicore numba scipy PyYAML pandas
```
=> Decouple linear from torch libraries

README.md, docs/cli/ov_data_format.rst, main.py
This is a workaround to avoid pytorch installation issues from affecting linear.
Linear still has dependencies beyond what is strictly necessary, but fixing that needs a larger refactoring.
=> Patching main.py to allow linear to run with pytorch 1.10

libmultilabel/utils.py
**Description** Add try-catch to `utils.AttributeDict` for `copy.deepcopy()`.
=> Add try-catch to `utils.AttributeDict`

example_config/MIMIC-50/bigru.yml, example_config/MIMIC-50/caml.yml, example_config/MIMIC-50/caml_tune.yml, example_config/MIMIC-50/cnn.yml, libmultilabel/metrics.py, libmultilabel/nn/data_utils.py, libmultilabel/nn/model.py, libmultilabel/nn/nn_utils.py, main.py, torch_trainer.py
**Description** 
1. Use train labels by default. If `include_test_labels` is true, use labels in both training and test dataset.
2. Add class `Macro-F1` for calculating the mean f1 scores of ALL labels in the dataset like `torchmetrics==0.3.2` does.
=> Fix Macro-F1 & Use train labels by default

libmultilabel/nn/networks/labelwise_attention_networks.py
Fix the following error:
```
AttributeError: 'CNNLWAN' object has no attribute 'rnn_dim'
```
=> Hotfix: fix CNNLWAN

libmultilabel/nn/data_utils.py
**Description** Simplify logic for loading embedding.
=> Embedding normalization raises an error when loading from torchtext

example_config/MIMIC-50/caml_tune.yml, requirements_parameter_search.txt, search_params.py
**Description** Update ray version to 1.10.0 and remove workaround code.
- Fixed bug: [Best trail printing None when input a nested config](https://discuss.ray.io/t/best-trail-printing-none-when-input-a-nested-config/4427).
- Add `grpcio==1.43.0`.
=> Update ray version to 1.10.0

libmultilabel/nn/networks/modules.py
Background: There is an empty text error when running BiGRU on Wiki10-31K.
Before the commit: The error happens when calling pack_padded_sequence() with a length equals to 0.
After the commit: After clamping the length to at least 1, pack_padded_sequence() works fine in one training epoch.
Reference: https://github.com/pytorch/pytorch/issues/4582
=> length clamp to at least 1 for input of rnn

search_params.py
The default behavior of `get_best_config()` only considers the score in the last epoch of each trial.
Set `scope="all"` to consider the scores in all epochs.
=> fix: get the best score from all epoch

libmultilabel/nn/metrics.py
NDCG in torchmetrics leads to cuda out of memory in evaluation.
Please refer to [this issue](https://github.com/PyTorchLightning/metrics/issues/932) for more details.
The definition of NDCG in the comment is from [sklearn.metrics.ndcg_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.ndcg_score.html#sklearn.metrics.ndcg_score).
=> Fix NDCG cuda out of memory

libmultilabel/linear/preprocessor.py
If pandas infers wrong data type, it will cause errors later on.
=> Prevent pandas from inferring data type

libmultilabel/linear/preprocessor.py
1. Raise an invalid svm format situation: index not start from 1 but 0.
2. Add file path in the error msg
3. Add ``from None'' for simplifying the error msg. The original one print too much.
=> fix loading svm format issue: index start from 0

libmultilabel/nn/nn_utils.py, torch_trainer.py
All tests finished (13/13) on early_stop.
Other testing:
* KimCNN on EUR-Lex
```
python3 main.py --config example_config/EUR-Lex/kim_cnn.yml
```
|     Macro-F1     |     Micro-F1     |       P@1        |       P@5        |       RP@5       |      nDCG@5      |
|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|
|     17.7268      |     52.3257      |     78.1630      |     53.4230      |     58.0091      |     62.4636      |
* KimCNN on EUR-Lex and include validation data for training
```
python3 main.py --config example_config/EUR-Lex/kim_cnn.yml --merge_train_val
```
|     Macro-F1     |     Micro-F1     |       P@1        |       P@5        |       RP@5       |      nDCG@5      | …
=> Set strict to false for early stopping

libmultilabel/nn/data_utils.py
All tests finished (13/13) on bert_fix.
* Before (bert on EUR-Lex-57k)
| Another-Macro-F1 |     Macro-F1     |     Micro-F1     |       P@1        |       P@5        |       RP@5       |      nDCG@5      |
|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|
|      0.0199      |      0.0199      |      3.1096      |     16.1833      |      9.5867      |     11.2725      |     12.0958     |
* After (bert on EUR-Lex-57k)
| Another-Macro-F1 |     Macro-F1     |     Micro-F1     |       P@1        |       P@5        |       RP@5       |      nDCG@5      |
|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|
|     19.2394      | …
=> Fix bert base

requirements.txt
If we set up the lightning version to 1.6.5, the program will cause the following error.
After some testing, I found that we can simply update lightning version to 1.7.0 to fix it.
=> Update pytorch lightning version to 1.7.0

tests/docs/test_tutorial.sh
**Description** Add script to test tutorials after a new release (such as API changes).
- Compare test results in log files between the current branch and the master branch.
- Write report `test_tutorial_report.txt`.
```bash
PASSED  python3 docs/examples/linear_quickstart.py
...
```
- Test pass message
```
All tests finished (3/3) on test_tutorial. See test_tutorial_report.txt for details.
```
=> Test tutorials

requirements.txt
Set torchmetrics < 0.11.0. The API changes of the latest torchmetrics make nn test fail.
=> Set torchmetrics == 0.10.3

docs/Makefile, docs/conf.py
=> fix warning

libmultilabel/linear/preprocessor.py, libmultilabel/nn/data_utils.py, requirements.txt, setup.cfg
- Update APIs for `linear.read_libmultilabel_format` and `nn.data_utils._load_raw_data`: allow both file path and dataframe
- Remove deprecated args `warn_bad_lines` and `error_bad_lines` and set pandas version to >1.3.0
https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
=> Update APIs for reading data

libmultilabel/logging.py
Only import and configure the logging of the transformer module only if it exists.
This allows the user not to install the nn components when using only linear models.
=> Conditional import for transformers

search_params.py
Didn't change the key in search_param.py when updating load_datasets.
=> fix parameter search bug

libmultilabel/linear/tree.py
Use sparse matrices for flattened tree weights.
=> Use sparse weights for flattened tree

.github/workflows/python-publish.yml, README.md, docs/cli/ov_data_format.rst, setup.cfg
- Update the minimum Python version to 3.8  for [PyTorch 2.0](https://github.com/pytorch/pytorch/releases/tag/v2.0.0) (See Drop support for Python versions <= 3.7)
- Update related documents 
=> Update minimum python version to 3.8

docs/api/linear.rst, docs/examples/plot_dataset_tutorial.py, docs/examples/plot_linear_gridsearch_tutorial.py, docs/examples/plot_linear_quickstart.py, docs/examples/plot_linear_tree_tutorial.py, libmultilabel/linear/__init__.py, libmultilabel/linear/data_utils.py, libmultilabel/linear/preprocessor.py, linear_trainer.py
1. Separate loading from preprocessing (now closer to scikit-learn style)
2. Preprocessor now accepts user-defined tf-idf params
3. read_*_format() becomes private. Users have only one way to load data, i.e., load_dataset().
4. Thanks to 3., text and labels can only be access by "x" and "y", respectively, no more "text" or "labels". 
5. Update tutorials
**To-do:**
1. Further investigate if the preprocessor can be embedded into sklearn's pipeline
**Before:**
from libmultilabel import Preprocessor
\# Load & Preprocessing
preprocessor = Preprocessor(data_format="txt", include_test_labels=False, remove_no_label_dat=False)
datasets = preprocessor.load_data("data/eur-lex/train.txt", "data/eur-lex/test.txt")
**After:**
from libmultilabel.linear import load_dataset, Preprocessor
\# Load
datasets …
=> Rewrite Preprocessor

example_config/rcv1/l2svm_svm_format.yml, libmultilabel/linear/preprocessor.py
If the data format is svm then `x` is not assigned.
This was untested because none of our example configs use svm format.
I added a config file, but I can't think of a good file name, suggestions are highly welcome.
=> Fixed svm data format

requirements_parameter_search.txt
The version of ray should be 2.2.0, otherwise there will be some error. Also, the version of grpcio is changed due to some conflicts.
=> Fix version of ray in parameter search requirement

libmultilabel/nn/data_utils.py
Links (mirror site) to pretrained glove vectors not found. 
We need a hotfix before TorchText updates the links.
See details: https://github.com/pytorch/text/issues/2188
=> [TorchText] Bug: Hotfix Glove URLs

search_params.py
Fix some bugs in search_params.py:
1. Test result won't dump to log.
2. Logging message is the same for retrain and no retrain.
- All tests finished (13/13) on fix-search_params.py-bugs. See test_report.txt for details.
=> fix bugs of search_params;

libmultilabel/linear/tree.py
Change the storage format of the node's weights from csr_matrix to csc_martix to reduce memory usage.
=> change the storage format of node's weights to csc_matrix

libmultilabel/linear/data_utils.py
Fix a bug introduced in commit 72c6458.
`read_svm_format` should allow samples with no labels. However, the current version would trigger an exception.
The error can be produced by using any `.svm` file containing samples with no labels, or [the ECtHR (A) dataset](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multilabel/ecthr_a_lexglue_tfidf_train.svm.bz2).
Because `labels` is `None` when no label is associated with an example, we should check whether it is `None` before calling `split()`.
If any APIs in quickstarts or tutorials are modified, please run this test to check if the current examples can run …
=> Fix read_svm_format when no label is associated with an example

libmultilabel/linear/linear.py
This PR replaces the original SCutFBR.1 implementation of `train_thresholding` with the [micromacro method](https://www.csie.ntu.edu.tw/~cjlin/papers/thresholding/smooth_acm.pdf).
=> Replace existing thresholding with micromacro

docs/api/linear.rst, libmultilabel/linear/metrics.py
=> Add linear recall

libmultilabel/common_utils.py, search_params.py, torch_trainer.py
Currently, logs.json contains many completely unrelated config items, which is very misleading.
For example, logs from a linear run has
```
"val_size": 0.2,
"epochs": 10000,
"batch_size": 16,
"optimizer": "adam",
"learning_rate": 0.0001,
"momentum": 0.9,
"lr_scheduler": null,
"patience": 5,
"early_stopping_metric": "P@1",
"init_weight": "kaiming_uniform",
"loss_function": "binary_cross_entropy_with_logits",
"metric_threshold": 0.5,
```
These items looks reasonable enough that a user may think they are relevant to linear models, which is wrong.
This PR removes all config values that has never been read, which solves this problem.
~~There are potentially problems with search_params.py because config is serialized when being passed as an argument to other processes. I haven't checked this …
=> Only log relevant config

docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
As title, a tutorial for using main.py for retraining is necessary. The preview of the tutorial is [here](https://www.csie.ntu.edu.tw/~b09902131/html/tutorials/Parameter_Selection_for_Neural_Networks.html#re-training-using-main-py).
=> Add retrain tutorial

libmultilabel/common_utils.py, libmultilabel/linear/linear.py, libmultilabel/linear/tree.py, linear_trainer.py
1. Align with nn
2. Reproduce results
* (Align with nn) Now models will remember the task type (multiclass=True or False) after training. The task type will then be used during testing process. 
* Raise an error when users try to train binary/multiclass models with "tree".
* Raise an error when the ratio of unlabeled instances is larger than 10% in the training dataset.
| Linear | ECtHR (A) (unlabeled) | ECtHR (B) (unlabeled) | SCOTUS | EUR-LEX | LEDGAR | UNFAIR-ToS (unlabeled) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| one-vs-rest | 69.6/54.6 | 75.6/68.8 |  78.1/68.9  | 72.0/55.4  | 86.4/80.0  | 70.1/72.3  |
| threshold | 74.1/68.4 | 77.2/73.6 | 79.1/71.8  | 74.6/62.3 | 86.2/79.5 | 75.7/77.1 |
| cost-sensitive | …
=> detect task type

libmultilabel/nn/metrics.py
The original NDCG metric calculates scores for one instance at a time, which is inefficient. The new NDCG metric calculate scores in batch.
Number of labels = 100
Batch size = 40
Number of batchs = 100
Effective number of validation samples = 4000
=> Batch NDCG

libmultilabel/nn/data_utils.py
For large datasets, tokenization can take a lot of time (40 mins for AmazonCat-13K using nltk.word_tokenize). Since Instances are independent from each other during tokenization, multiprocessing can speed up the process.
Currently LibMultiLabel didn't produce any information during tokenization. Users could assume the program gets stuck if they provide a large dataset. Thus, one extra thing I did is adding tqdm to tokenization, which helps users to know what LibMultiLabel is doing. 
If any APIs in quickstarts or tutorials are modified, please run this test to check if the current examples can run correctly after the …
=> Speed Up Tokenization Through Multiprocessing

.github/workflows/basic_test.yml, .gitignore, docs/api/api.rst, docs/cli/ov_data_format.rst, libmultilabel/nn/__init__.py, main.py, requirements.txt, requirements_nn.txt, setup.cfg
Make nn dependencies optional. For installing from PyPI
```bash
pip install libmutlilabel      # installs linear dependencies only
pip install libmultilabel[nn]  # installs nn dependencies as well
```
PyPI has no parameter search version because no code in the library uses ray.
Similarly,
```bash
pip install -r requirements.txt     # installs linear dependencies only
pip install -r requirements_nn.txt  # installs nn dependencies as well
```
=> Make nn dependencies optional

libmultilabel/linear/metrics.py, setup.cfg
#339 introduced a bug for recall.
In the case where there are no labels for an instance, its recall should be 0, not 1.
`nan_to_num` by default sets NaN to 0, the changes in F1 is to make this explicit.
=> Fixed recall for no label instances

docs/api/linear.rst, docs/requirements.txt, main.py
Also fixed sphinx version to 5 because it broke compatibility at some point around 5.3.0.
I cannot find documentation for nn `get_metrics`, is this an oversight?
=> Added link to implementation docs in metrics section

libmultilabel/common_utils.py, main.py, run_and_store_results.py, search_params.py
In many situations, developers may want to measure the running time of functions. The original Timer in LibMultiLabel is no more convenient than using the time package directly. The new lightweight timer is a decorator and is easy to use.
usage 1:
```python
import time
from libmultilabel.common_utils import timer
@timer
def a ():
time.sleep(3)
a()
```
```
INFO:lightning.pytorch.utilities.rank_zero:Finished 'a' in 3.00 seconds
```
usage 2:
```python
def a ():
time.sleep(3)
timer(a)()
```
```
INFO:lightning.pytorch.utilities.rank_zero:Finished 'a' in 3.00 seconds
```
If any APIs in quickstarts or tutorials are modified, …
=> A Lighter Timer

libmultilabel/nn/metrics.py, setup.cfg
=> Fix top_k in metrics.py

libmultilabel/linear/data_utils.py
For newer scipy versions, there is no `scipy.frombuffer`.
scipy used to contain all numpy functions, but this has since been deprecated and removed.
=> Fixed deprecated/removed scipy API

requirements.txt, setup.cfg
We are using a feature [not supported by sklearn:](https://scikit-learn.org/stable/developers/develop.html)
> In addition, every keyword argument accepted by __init__ should correspond to an attribute on the instance.
This PR is a temporary patch to use unsupported behaviour from sklearn 1.2.2 before a comprehensive fix can be implemented.
=> Fixed sklearn version before GridSearchCV is fixed

libmultilabel/linear/utils.py, requirements.txt, setup.cfg
When using sklearn >=1.3.0, we'll catch an error when fitting GridSearchCV: 
> AttributeError: 'GridSearchCV' object has no attribute 'pipeline'
This PR fix this by letting every keyword argument accepted by our customized GridSearchCV correspond to an attribute of the sklearn's original GridSearchCV.
=> Fix GridSearchCV to support sklearn>=1.3.0

libmultilabel/nn/model.py
The original prediction function uses shared_step which calculates losses, though it later discards the loss. This procedure introduces complexity to algorithms using reduced label space. With the current prediction function, test labels has to be mapped to the reduced space before doing prediction, which is unnecessary and could be avoided.
=> Don't Calculate Loss in Prediction

libmultilabel/linear/utils.py, run_and_store_results.py
Fix 2 times memory usage issue when using pickle.dump
- [ X ] Not Applicable (i.e., the PR does not include API changes.)
- [ X ] Not Applicable (i.e., the PR does not include API changes.)
=> add a flag to use the latest protocol in pickle dump

tests/basic.sh
1. Add new dataset AmazonCat-13K
2. Add one more feature (lipsum) to the fake data
3. Allow val_size to be an integer larger than 10. Add new test parameters save_k_predictions and cluster_size.
=> Increase the Capability of Autotest & Add One More Feature to Fake Text

docs/api/linear.rst, libmultilabel/linear/linear.py, libmultilabel/linear/tree.py, linear_trainer.py
To document the API of `beam_width`, models are no longer black boxes and have a public function `predict_values`.
=> Added CLI beam width functionality

libmultilabel/nn/attentionxml.py, libmultilabel/nn/model.py, libmultilabel/nn/nn_utils.py
- Remove `embed_vecs` from Model() for AttentionXML.
- Reduce AmazonCat-13K `model_*.ckpt` from 5.6G to 4.3G.
- Test results
**attentionxml / Wiki10-31K**
|              |       P@1        |       P@3        |       P@5        |       RP@3       |       RP@5       |      nDCG@3      |      nDCG@5      |
|-------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|
| this PR       |      0.8696      |      0.7744      |      0.6770      |      0.7745      |      0.6774      |      0.7971      |      0.7241      |
| master       |      0.8696      |      0.7744      |      0.6770      |      0.7745      |      0.6774      |      0.7971      |      0.7241      |
**attentionxml / AmazonCat-13K**
| …
=> Remove `embed_vecs` from Model and PLTModel

libmultilabel/linear/metrics.py
Python 3.12 generates `SyntaxWarning` instead of `DeprecationWarning` for escape sequence `\d`.
https://docs.python.org/3/whatsnew/3.12.html#other-language-changes
=> Update regex syntax for python3.12

docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
Update LibMultiLabel Documentation: revise  flag --no_merge_train_val to  flag --merge_train_val because the flag --no_merge_train_val is no longer used 
=> Update Docs by revising --no_merge_train_val to --merge_train_val

requirements_parameter_search.txt, search_params.py
1. Add shorthand for --config
2. Since 2.24.0, using local_dir in ray.tune will raise an error. a minimum version requirement is set for ray[tune]. The first deprecation comment occurs in 2.5.0.
3. Upgrade ray.tune API from 1.0 style to 2.0 because the documentation of the 1.0-style API is no longer updated.
**Results:**
Before:
After:
=> Update Ray Argument

search_params.py
merge_train_val is already in config
=> Remove Redundant merge_train_val

requirements_nn.txt, setup.cfg
- Torchtext is incompatible with the latest PyTorch 2.4.0, which makes the test fail.
- Torchtext stopped being updated in Apr. 2024, and the latest version will be fixed at 0.18.0 (compatible with Pytorch 2.3). See Pytorch/Torchtext dependency [here](https://github.com/pytorch/text/releases).
=> Fix Autotest: Set Pytorch <=2.3 to resolve torchtext dependency issue

libmultilabel/linear/tree.py, requirements.txt
=> estimate and print tree model size

example_config/EUR-Lex/tree_l2svm.yml, example_config/rcv1/l2svm.yml, example_config/rcv1/l2svm_svm_format.yml, libmultilabel/linear/linear.py, libmultilabel/linear/tree.py
Change the default optimizer to l2 dual coordinate descent method because the method is efficient in training speed and effective in "sparsify" model weights to save space,
=> change the defaut optimizer to l2 cddual in EUR-lex config
