ASUS-AICS/LibMultiLabel

requirements.txt, utils/__init__.py
Description: add `requirement.txt`
Issue #2 requirements.txt is needed for environment setting.
=> Add requirements.txt

README.md
**Description**: add -p to mkdir data/rcv1
=> Update README.md - recursive mkdir

example_config/MIMIC-50/caml.yml, example_config/MIMIC-50/cnn.yml
Add MIMIC-50 configs: `caml.yml`, `cnn.yml`.
=> Add MIMIC-50 configs.

README.md, evaluate.py, example_config/rcv1/kim_cnn.yml, example_config/rcv1/xml_cnn.yml, main.py, model.py, networks/inner.py, networks/kim_cnn.py, networks/xml_cnn.py, utils.py
1. allow specifying K for top K prediction
2. update model arguments
3. remove inner.py
4. fix early stopping condition
=> Allow specifying K for top K prediction and update model arguments

README.md
=> hotfix: update README

example_config/MIMIC-50/caml.yml, main.py, networks/caml.py, networks/kim_cnn.py, networks/xml_cnn.py
1. Add descriptions for the order between activation function and max-pooling
2. Update CAML parameter
=> Add descriptions and update CAML

README.md, requirements.txt, requirements_parameter_search.txt
1. Add `requirements_parameter_search.txt`.
2. Update README (#hyperparameter-search).
=> Move ray[tune] and related packages to requirements_parameter_search.txt.

README.md, example_config/MIMIC-50/caml_tune.yml, example_config/rcv1/cnn_tune.yml, search_params.py
1. Add `search_alg` to config.
2. Initialize sample spaces without `search_params`.
=> Search config

libmultilabel/model.py, libmultilabel/networks/kim_cnn.py
#42 Some minor issues(1) & (2).
=> Update comment for kim_cnn & align logits in train_step & predict.

search_params.py
Our hyperparameter script does not have the same result. According to ray's FAQ, we should to set seed in both the main function and `setup()`.
https://docs.ray.io/en/master/tune/tutorials/overview.html
=> [Hotfix] Set seed in setup() to ensure the reproducibility.

libmultilabel/evaluate.py, requirements_parameter_search.txt, search_params.py
1. Add `ray==1.4.0` to `requirments_parameter_search.txt`.
2. Add final report in the end.
3. Fix bug: cannot monitor metrics not in `P@k` or `R@k` like `Micro-F1` and `Macro-F1`
=> [Parameter search] Reporter

libmultilabel/model.py, libmultilabel/utils.py
1. add `dump_log` to `validation_epoch_end`
2. `utils.dump_log`: save config to `logs.json` with dict(config)
=> [Hotfix] dump_log

libmultilabel/model.py
Reproducibility is ensured in https://github.com/ASUS-AICS/LibMultiLabel/tree/reproduce
=> Remove to device in network

libmultilabel/networks/base.py, libmultilabel/networks/caml.py
Add more description to `caml.py` including naming & shapes.
=> Add more description for CAML.

libmultilabel/data_utils.py, libmultilabel/metrics.py, libmultilabel/model.py, main.py
1. Use TorchMetrics to evaluate on GPU.
2. Allow customized torchmetrics.Metric objects.
=> Torchmetrics

example_config/EUR-Lex/kim_cnn.yml, example_config/EUR-Lex/xml_cnn.yml, example_config/MIMIC-50/caml.yml, example_config/MIMIC-50/caml_tune.yml, example_config/MIMIC-50/cnn.yml, example_config/rcv1/cnn_tune.yml, example_config/rcv1/kim_cnn.yml, example_config/rcv1/xml_cnn.yml, libmultilabel/model.py, libmultilabel/networks/base.py, libmultilabel/networks/caml.py, libmultilabel/networks/kim_cnn.py, libmultilabel/networks/xml_cnn.py, main.py, search_params.py
- **network_config**
- Pass in `network_config` instead of `kwargs` to `model.network`.
- Add `network_config` to all yaml files, such as:
```yaml
network_config:
activation: tanh
dropout: 0.2
filter_sizes: [10]
num_filter_per_size: 50
```
- Check config in `main.py`.
- Add more comments to networks.
=> Set network config in the yaml file

example_config/MIMIC-50/caml_tune.yml, example_config/rcv1/cnn_tune.yml, libmultilabel/model.py, main.py
- Merge `Model` and `MultiLabelModel` to `Model`.
- Add comments to `shared_step` and `predict_step`.
=> Merge `Model` and `MultiLabelModel`

example_config/MIMIC-50/caml.yml, example_config/MIMIC-50/caml_tune.yml, example_config/MIMIC-50/cnn.yml, libmultilabel/data_utils.py, main.py, search_params.py
**Description**  Add `--normalize` to config to decide if we should normalize the word embeddings by:
```python
vector = vector  / float(np.linalg.norm(vector) + 1e-6)
```
=> Add normalize as an argument

libmultilabel/linear/linear.py
shall change `evaluate` to `predict_values`
=> update __all__ with predict_values

example_config/MIMIC-50/bigru.yml
**Description** `normalize` to `normalize_embed`
=> [Hotfix] Update bigru.yml

search_params.py
**Description** Update model initialization in `search_params.py`.
- Pass in network to Model()
- Replace normalize with normalize_embed
=> Update model initialization

README.md
#83 Put example to show the format of `vocab_file`.
=> Add example to the format of `vocab_file`

example_config/MIMIC-50/caml_tune.yml, libmultilabel/nn/nn_utils.py, search_params.py, torch_trainer.py
1. Use `ModelCheckpoint` in `trainer.callback`. (Issue #88 )
2. Fix arguments to trainer.
- the model should be saved in `checkpoint_dir`
- pass in `silent` and `use_cpu` while initializing `Trainer`.
=> Fix trainer issues

main.py
**Description** Remove network config from `argparse`.
=> Remove network config from argparse.

docs/cli/nn.rst
**Description** close issue #105
=> Update load_checkpoint -> checkpoint_path

libmultilabel/utils.py, requirements.txt
1. torchmetrics: 0.6.0
2. Remove unused import.
=> Update torchmetrics to 0.6.0

libmultilabel/nn/data_utils.py, torch_trainer.py
**Description** Train without validation when `val_size` is set to 0.
=> Train without the validation set

README.md
**Description** Remove PyPi installation from the README.
=> Remove installation from README.md

docs/cli/linear.rst, libmultilabel/linear/linear.py, libmultilabel/linear/preprocessor.py, main.py
With updates to main.py to accommodate the extra methods.
Also update to Preprocessor API.
=> Added thresholding and cost-sensitive

docs/cli/cli.rst, docs/cli/data_format.rst
**Description** Add links to the datasets.
=> Add link to the datasets

example_config/MIMIC-50/caml_tune.yml, example_config/rcv1/cnn_tune.yml, libmultilabel/nn/nn_utils.py, main.py, tests/autotest.sh, torch_trainer.py
**Description** Add script for auto-testing.
- Add `tests/autotest.sh`.
- Add new arguments:
- `limit_train_batches` / `limit_val_batches` / `limit_test_batches`: train/val/test part of the dataset for each epoch
=> Add script for auto-testing

requirements.txt, setup.cfg
This accelerates linear methods without API changes.
=> updated requirements

docs/api/api.rst, docs/examples/nn_quickstart.py
**Description**  Remove `datatime` import from the nn API example.
=> Update example of NN API

docs/examples/nn_quickstart.py
**Description** Update `nn_quickstart.py` for `nn.data_utils.load_datasets`.
> This example should be updated after the next release (v0.2.0).
> Dependency: #126
=> Update example for new NN API

docs/api/api.rst, docs/api/linear.rst, docs/api/linear_tutorial.rst, docs/api/nn.rst, docs/api/nn_tutorial.rst, docs/examples/linear_quickstart.py, docs/index.rst, libmultilabel/linear/linear.py, libmultilabel/linear/preprocessor.py
Includes a new linear tutorial and moving neural network tutorial to a standalone page.
Some links are "placeholder" currently because the pages don't exist yet.
=> Updated API Getting Started

.github/workflows/python-publish.yml
**Description** Add workflow to trigger pypi upload after publishing a new release.
=> Automating PyPI releases with Github Actions

linear_trainer.py, main.py, tests/autotest.sh, torch_trainer.py
`config.predict_out_path` moved from `torch_trainer.py` to `main.py`, similar to other path computations.
=> Added linear tests and save k prediction

setup.cfg
**Description** Release 0.1.2 after fixing macro-f1 score.
=>  Update release version: 0.1.2

libmultilabel/linear/linear.py, libmultilabel/linear/metrics.py
Fixes bug with label order and changes cost-sensitive to use a single `-c` value.
Silences useless warnings in metrics.
=> Linear bugfix and cost-sensitive modification

example_config/EUR-Lex/bigru_tune.yml
**Description** Add BiGRU config in the user guide.
=> Add BiGRU config

example_config/rcv1/cnn_tune.yml, example_config/rcv1/kim_cnn.yml
=> update rcv1 KimCNN model and tuning procedure

example_config/EUR-Lex/bigru_lwan.yml, example_config/EUR-Lex/bigru_lwan_tune.yml
=> Add `example_config/EUR-Lex/bigru_lwan.yml` for the user guide

setup.cfg
=> Update release version: 0.1.3

search_params.py
=> Add `if __name__ == '__main__':` to `search_params.py` 

example_config/MIMIC-50/caml.yml, libmultilabel/nn/networks/caml.py, libmultilabel/nn/networks/labelwise_attention_networks.py
- Naming: use `Q`, `Z`, and `E` as the variable names
- Remove `activation` from `caml.py`.
=> Update CAML naming

example_config/EUR-Lex-57k/README.md, example_config/MIMIC/README.md
=> fix config link

search_params.py
- Evaluate on the test set after parameter search if the test set is given
- Save logs for the best parameters in best_trial/
- Dump the best parameters in best_trial/params.yml
- Rename experiment directory by [data_name]_[config_name]_[time]
=> Improve logs for parameter search

libmultilabel/nn/networks/bert_attention.py, search_params.py
- Support BERT-LWAN
- Fix the tokenization for tuning BERT-based models
=> Fix bert tuning

docs/api/nn_networks.rst
The table of contents had to be maintained manually, so I removed it for now.
There is a package for automatically creating a table of contents, but it introduces some new issues and complexity.
=> Automatically generate nn docs

libmultilabel/nn/networks/modules.py, search_params.py
search_params.py now uses same timer code as main.py.
Fixed some typos in comments.
=> Minor fixes

example_config/EUR-Lex-57k/README.md, example_config/EUR-Lex-57k/bert_lwan.yml, example_config/EUR-Lex-57k/bert_lwan_tune.yml
Add configs, result, and references
=> Add configs of BERT-BASE-LWAN on EURLEX57K

example_config/EUR-Lex-57k/bigru_lwan_tune.yml, example_config/EUR-Lex-57k/cnn_lwan_tune.yml, example_config/EUR-Lex/bigru_lwan_tune.yml, example_config/MIMIC-50/bigru_lwan_tune.yml, example_config/MIMIC-50/caml_tune.yml, example_config/MIMIC/bigru_lwan_tune.yml, example_config/MIMIC/cnn_lwan_tune.yml, example_config/rcv1/cnn_tune.yml, libmultilabel/linear/preprocessor.py, libmultilabel/nn/data_utils.py, linear_trainer.py, main.py, search_params.py, torch_trainer.py
+ Modify read_libsvm_format so that it can handle samples with no positive labels
+ Add option 'keep_zero_labels' in both nn and linear modules so that such samples can be kept optionally.
=> Handle samples with no positive labels

docs/api/nn_tutorial.rst, docs/examples/nn_quickstart.py, libmultilabel/nn/data_utils.py, libmultilabel/nn/metrics.py, libmultilabel/nn/model.py, libmultilabel/nn/networks/caml.py, libmultilabel/nn/networks/kim_cnn.py, libmultilabel/nn/networks/labelwise_attention_networks.py, libmultilabel/nn/networks/modules.py, libmultilabel/nn/networks/xml_cnn.py, libmultilabel/nn/nn_utils.py, requirements.txt, search_params.py, torch_trainer.py
See the [document](https://hackmd.io/h5nPzjs3RTKdDPC4AEXb_g) for more details.
=> Update pytorch version

README.md, example_config/EUR-Lex-57k/bert_lwan_tune.yml, example_config/EUR-Lex-57k/bigru_lwan_tune.yml, example_config/EUR-Lex-57k/cnn_lwan_tune.yml, example_config/EUR-Lex-57k/kim_cnn_tune.yml, example_config/EUR-Lex/bigru_lwan_tune.yml, example_config/EUR-Lex/cnn_lwan_tune.yml, example_config/EUR-Lex/kim_cnn_tune.yml, example_config/MIMIC-50/bert_attention.yml, example_config/MIMIC-50/bigru_lwan.yml, example_config/MIMIC-50/bigru_lwan_tune.yml, example_config/MIMIC-50/caml.yml, example_config/MIMIC-50/caml_tune.yml, example_config/MIMIC-50/cnn.yml, example_config/MIMIC/bigru_lwan.yml, example_config/MIMIC/bigru_lwan_tune.yml, example_config/MIMIC/cnn_lwan.yml, example_config/MIMIC/cnn_lwan_tune.yml, example_config/MIMIC/kim_cnn.yml, example_config/MIMIC/kim_cnn_tune.yml, example_config/Wiki10-31K/bigru_lwan_tune.yml, example_config/Wiki10-31K/cnn_lwan_tune.yml, example_config/Wiki10-31K/kim_cnn_tune.yml, example_config/rcv1/cnn_tune.yml, libmultilabel/linear/preprocessor.py, libmultilabel/nn/data_utils.py, linear_trainer.py, main.py, search_params.py, torch_trainer.py
Test kim_cnn on EUR-Lex, kim_cnn on MIMIC, and l2svm on unfair_tos,
and they show consistent results between the current branch and master branch.
* kim_cnn on EUR-Lex
* command
```
python3 main.py --config example_config/EUR-Lex/kim_cnn.yml --epochs 2
``` 
* results
|     Macro-F1     |     Micro-F1     |       P@1        |       P@5        |       RP@5       |      nDCG@5      |
|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|
|      0.7314      |     11.7359      |     38.7840      |     22.3286      |     23.9978      |     27.0415      |
* kim_cnn on MIMIC
* command
```
python3 main.py --config example_config/MIMIC/kim_cnn.yml --epochs 2
```
* results
|     Macro-F1     |     Micro-F1     |       P@15       | …
=> Modify the default behavior to keep no label data

example_config/EUR-Lex/bigru_lwan.yml, example_config/EUR-Lex/bigru_lwan_tune.yml, example_config/EUR-Lex/cnn_lwan.yml, example_config/EUR-Lex/cnn_lwan_tune.yml, example_config/EUR-Lex/kim_cnn.yml, example_config/EUR-Lex/kim_cnn_tune.yml, example_config/EUR-Lex/xml_cnn.yml, example_config/Wiki10-31K/bigru_lwan.yml, example_config/Wiki10-31K/bigru_lwan_tune.yml, example_config/Wiki10-31K/cnn_lwan.yml, example_config/Wiki10-31K/cnn_lwan_tune.yml, example_config/Wiki10-31K/kim_cnn.yml, example_config/Wiki10-31K/kim_cnn_tune.yml, example_config/rcv1/cnn_tune.yml, example_config/rcv1/l2svm.yml, example_config/rcv1/xml_cnn.yml, libmultilabel/nn/data_utils.py, search_params.py
These datasets don't have pre-split validation data.
=> Fixed config validation file

.github/workflows/basic_test.yml, example_config/EUR-Lex/bigru_lwan.yml, example_config/EUR-Lex/bigru_lwan_tune.yml, example_config/EUR-Lex/cnn_lwan.yml, example_config/EUR-Lex/cnn_lwan_tune.yml, example_config/EUR-Lex/kim_cnn.yml, example_config/EUR-Lex/kim_cnn_tune.yml, example_config/EUR-Lex/xml_cnn.yml, example_config/Wiki10-31K/bigru_lwan.yml, example_config/Wiki10-31K/bigru_lwan_tune.yml, example_config/Wiki10-31K/cnn_lwan.yml, example_config/Wiki10-31K/cnn_lwan_tune.yml, example_config/Wiki10-31K/kim_cnn.yml, example_config/Wiki10-31K/kim_cnn_tune.yml, example_config/rcv1/cnn_tune.yml, example_config/rcv1/l2svm.yml, example_config/rcv1/xml_cnn.yml, libmultilabel/nn/data_utils.py, libmultilabel/nn/metrics.py, libmultilabel/nn/networks/xml_cnn.py, libmultilabel/nn/nn_utils.py, main.py, search_params.py, tests/basic.sh, tests/short.sh
This test runs example configs with fake data, ensuring no hard errors occur.
This is relatively fast and is intended to be ran as a github action before merging anything to master.
Also included is several xmlcnn fixes.
This PR depends on #200.
=> Fast basic test

example_config/EUR-Lex-57k/bert_lwan_tune.yml, example_config/EUR-Lex-57k/bigru_lwan_tune.yml, example_config/EUR-Lex-57k/cnn_lwan_tune.yml, example_config/EUR-Lex-57k/kim_cnn_tune.yml, example_config/EUR-Lex/bigru_lwan_tune.yml, example_config/EUR-Lex/cnn_lwan_tune.yml, example_config/EUR-Lex/kim_cnn_tune.yml, example_config/MIMIC-50/bigru_lwan_tune.yml, example_config/MIMIC/bigru_lwan_tune.yml, example_config/MIMIC/cnn_lwan_tune.yml, example_config/MIMIC/kim_cnn_tune.yml, example_config/Wiki10-31K/bigru_lwan_tune.yml, example_config/Wiki10-31K/cnn_lwan_tune.yml, example_config/Wiki10-31K/kim_cnn_tune.yml, example_config/rcv1/cnn_tune.yml
**Description** Add `add_special_tokens: False` to all tune-related config.
=> Update tune config

README.md, docs/index.rst, example_config/EUR-Lex-57k/bert_lwan_tune.yml, example_config/EUR-Lex-57k/bigru_lwan_tune.yml, example_config/EUR-Lex-57k/cnn_lwan_tune.yml, example_config/EUR-Lex-57k/kim_cnn_tune.yml, example_config/EUR-Lex/bigru_lwan_tune.yml, example_config/EUR-Lex/cnn_lwan_tune.yml, example_config/EUR-Lex/kim_cnn_tune.yml, example_config/MIMIC-50/bigru_lwan_tune.yml, example_config/MIMIC/bigru_lwan_tune.yml, example_config/MIMIC/cnn_lwan_tune.yml, example_config/MIMIC/kim_cnn_tune.yml, example_config/Wiki10-31K/bigru_lwan_tune.yml, example_config/Wiki10-31K/cnn_lwan_tune.yml, example_config/Wiki10-31K/kim_cnn_tune.yml, example_config/rcv1/cnn_tune.yml, libmultilabel/nn/data_utils.py, libmultilabel/nn/metrics.py, libmultilabel/nn/model.py, libmultilabel/nn/nn_utils.py, main.py, torch_trainer.py
**Description** 
- Add `--multiclass` and update the related files
- Test on LEDGAR
|     Macro-F1     |     Micro-F1     |
|-----------------:|-----------------:|
|     80.5773      |     86.9000      |
- after PR #203
=> Add multiclass

README.md, docs/index.rst
=> Add multiclass to README

requirements.txt, requirements_parameter_search.txt, search_params.py
Handle the issue https://github.com/ray-project/ray/issues/28197.
=> Fix Ray parameter search

libmultilabel/linear/preprocessor.py, libmultilabel/nn/data_utils.py, libmultilabel/nn/metrics.py, libmultilabel/nn/model.py, libmultilabel/nn/networks/__init__.py, libmultilabel/nn/networks/bert.py, libmultilabel/nn/networks/bert_attention.py, libmultilabel/nn/networks/caml.py, libmultilabel/nn/networks/kim_cnn.py, libmultilabel/nn/networks/labelwise_attention_networks.py, libmultilabel/nn/networks/modules.py, libmultilabel/nn/networks/xml_cnn.py, libmultilabel/nn/nn_utils.py, main.py, search_params.py, torch_trainer.py
=> Auto-format python files (skip E501)

libmultilabel/nn/model.py
**Description**: `--save_k_predictions` not work
=> Set data_loader_idx to 0 in predict_step()

docs/cli/linear.rst
Update document for `linear.binary_and_multiclass`.
=> Update document for linear.binary_and_multiclass

search_params.py
After parameter search, if not merging training and validation data, search_params.py should load the model from the parameter search process instead of retrain. This PR fix this problem.
=> update to really no retrain

README.md, docs/cli/ov_data_format.rst, setup.cfg
Update the package version & bump version to 0.1.7.
=> Update release version: 0.1.7

docs/api/linear.rst
=> Add API doc for linear grid search

docs/Makefile
=> Generate flags before make doc

docs/Makefile, docs/_static/custom.css, docs/conf.py, docs/examples/README.txt, docs/readme, docs/requirements.txt
Configuration files for using sphinx gallery.
=> Configuration for sphinx gallery.

docs/api/api.rst, docs/examples/plot_KimCNN_tutorial.py, docs/examples/plot_bert_tutorial.py, docs/examples/plot_linear_tutorial.py, docs/index.rst
=> Quickstart generated by sphinx gallery. 

setup.cfg
=> Update release version: 0.1.8

libmultilabel/linear/preprocessor.py, libmultilabel/nn/data_utils.py
=> add quoting=csv.QUOTE_NONE

docs/api/api.rst, docs/api/quickstart.rst, docs/cli/ov_data_format.rst, docs/cli/quickstart.rst, docs/cli_index.rst, docs/index.rst, docs/library_index.rst, docs/tutorial.rst
Reorganize the document
- [ x ] Not Applicable (i.e., the PR does not include API changes.)
- [ x ] Not Applicable (i.e., the PR does not include API changes.)
- [ x ] Not Applicable (i.e., the PR does not include API changes.)
=> Reorganize the document

libmultilabel/nn/data_utils.py, torch_trainer.py
Let load_datasets can also load libmultilabel format in dataframe.
=> NN load_datasets loading dataframe.

setup.cfg
=> version update

docs/api/api.rst, docs/examples/plot_dataset_tutorial.py, docs/library_index.rst, docs/tutorial.rst
New dataset tutorial.
https://www.csie.ntu.edu.tw/~b09902131/html/auto_examples/plot_dataset_tutorial.html#
=> Add custom dataset tutorial.

docs/examples/plot_dataset_tutorial.py, docs/tutorial.rst
=> Update document link

docs/tutorial.rst
=> Fix document link

setup.cfg
=> Update release version: 0.1.10

docs/examples/plot_linear_gridsearch_tutorial.py
Add link to "Feature Generation and Parameter Selection for Linear Methods"
=> Add link for LIBLINEAR OPTIONS

libmultilabel/linear/preprocessor.py, libmultilabel/nn/data_utils.py
The ``path`` in the original file is not changed to the right variable. 
=> Load data bug fix

libmultilabel/linear/preprocessor.py, libmultilabel/nn/data_utils.py, tests/docs/test_examples.sh
=> Linear load_data  add type check.

libmultilabel/linear/preprocessor.py
`self.data_format == 'txt' or 'dataframe'` does not mean the correct thing.
=> Fixed wrong if statement

setup.cfg
Patch release due to the issue: #265 
=> Update release version: 0.1.11

tests/docs/test_examples.sh
=> Add new tutorials to test_example.sh

docs/examples/plot_linear_quickstart.py, libmultilabel/linear/linear.py
as title.
https://www.csie.ntu.edu.tw/~b09902131/html/auto_examples/plot_linear_quickstart.html
=> Update linear quickstart

docs/examples/plot_linear_gridsearch_tutorial.py, libmultilabel/linear/__init__.py, libmultilabel/linear/linear.py, libmultilabel/linear/metrics.py, libmultilabel/linear/preprocessor.py, libmultilabel/linear/tree.py, libmultilabel/linear/utils.py, linear_trainer.py, main.py
General minor fixes, see commit message for details.
If any APIs in the document are modified, please run this test after the APIs are released.
=> Random fixes

libmultilabel/linear/linear.py, libmultilabel/linear/tree.py, libmultilabel/linear/utils.py, linear_trainer.py
=> Add model name to linear models

example_config/EUR-Lex/tree_l2svm.yml, libmultilabel/linear/tree.py
Fixed missing parameter in `FlatModel` in tree.py. There will be an error otherwise.
Added an example config for tree models for basic tests.
=> Fixed missing parameter

docs/api/linear.rst, docs/examples/plot_linear_quickstart.py, libmultilabel/linear/linear.py, libmultilabel/linear/metrics.py, libmultilabel/linear/utils.py, libmultilabel/nn/metrics.py, libmultilabel/nn/model.py, libmultilabel/nn/nn_utils.py, linear_trainer.py, main.py
Added reset to linear metrics and updated docs.
=> Linear metric

setup.cfg
=> update release version 0.2.0

.gitmodules, docs/readme
=> Add bib in doc

libmultilabel/linear/linear.py, libmultilabel/linear/tree.py
=> Fixed edge case of zero instances and randint upper bound

docs/examples/plot_linear_gridsearch_tutorial.py, libmultilabel/linear/utils.py
- Raise error for `scoring` and update documents
=> Disable `scoring` in utils.GridSearchCV

setup.cfg
Update the package version to 0.2.1
=> Update release version: 0.2.1

example_config/MIMIC-50/bigru_lwan_tune.yml, example_config/MIMIC-50/caml_tune.yml, example_config/MIMIC/bigru_lwan_tune.yml, example_config/MIMIC/cnn_lwan_tune.yml, example_config/MIMIC/kim_cnn_tune.yml, example_config/Wiki10-31K/bigru_lwan_tune.yml, example_config/Wiki10-31K/cnn_lwan_tune.yml, example_config/Wiki10-31K/kim_cnn_tune.yml, example_config/rcv1/cnn_tune.yml
As title. I'm not sure the case for other example configs. So only MIMIC-50 are modified for now.
=> Modify example config early stopping metrics

setup.cfg
Update the package version to 0.3.0
=> Update release version: 0.3.0

setup.cfg
=> Update version to 0.3.1

setup.cfg
=> Update version to 0.3.2

example_config/EUR-Lex-57k/bert_lwan_tune.yml, example_config/EUR-Lex-57k/bigru_lwan_tune.yml, example_config/EUR-Lex-57k/cnn_lwan_tune.yml, example_config/EUR-Lex-57k/kim_cnn_tune.yml, example_config/EUR-Lex/bigru_lwan_tune.yml, example_config/EUR-Lex/cnn_lwan_tune.yml, example_config/EUR-Lex/kim_cnn_tune.yml, example_config/MIMIC-50/bigru_lwan_tune.yml, example_config/MIMIC-50/caml_tune.yml, example_config/MIMIC/bigru_lwan_tune.yml, example_config/MIMIC/cnn_lwan_tune.yml, example_config/MIMIC/kim_cnn_tune.yml, example_config/Wiki10-31K/bigru_lwan_tune.yml, example_config/Wiki10-31K/cnn_lwan_tune.yml, example_config/Wiki10-31K/kim_cnn_tune.yml, example_config/rcv1/cnn_tune.yml
Due to the scheduler feature, the two extra arguments are needed in example configs of parameter search.
=> add lr_scheduler and scheduler_config

docs/examples/plot_KimCNN_quickstart.py, libmultilabel/nn/networks/kim_cnn.py, libmultilabel/nn/networks/labelwise_attention_networks.py, libmultilabel/nn/networks/modules.py, libmultilabel/nn/networks/xml_cnn.py
1. Auto-format for lines longer than 120 words by Black.
2. Extend arguments accepted by Embedding. Now accept **freeze** .
=> Extend arguments accepted by Embedding

setup.cfg
=> Update version to 0.3.3

docs/readme
=> Add python 3.8 the doc readme

README.md, docs/cli/ov_data_format.rst, requirements.txt, setup.cfg
Fix versions: torch==1.13.1, torchtext==0.14.1, transformers==4.28.1
=> Fix torch, torchtext, and transformers versions

libmultilabel/linear/metrics.py
Previously, metrics were computed in an inefficient manner.
This wasn't a big issue because evaluation was not a bottleneck.
But for cross-validation, a lot of evaluation is required.
This is further aggravated if a lot of metrics is used.
This PR contains code that improves evaluation time significantly (e.g. 6x for experiments I'm running).
=> Added batched metrics

docs/index.rst
=> Release implementation document.

setup.cfg
=> Removed redundant line

libmultilabel/nn/data_utils.py
1. Fix wrong return type
2. Fix possible null pointer and key error
3. Add info while loading data
=> Enhance data_utils

setup.cfg
=> Fix error classifier in setup.cfg

main.py, tests/basic.sh
Add a new argument, which is the prerequisite of AttentionXML
=> add beam_width

README.md, docs/index.rst, main.py, setup.cfg
=> Remove `text` from titles

docs/readme
=> Update doc readme

libmultilabel/linear/linear.py, libmultilabel/linear/tree.py
=> fix some typos and consistency
